site_name: Trader Manual
site_url: https://theman360pe.github.io/trader-manual/   # important for GitHub Pages subfolder sites
use_directory_urls: true

nav:
  - Contents: index.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - toc.follow       # auto-scrolls the left nav ToC to the active section
    - navigation.top   # back-to-top button
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

plugins:
  - search
  - offline

markdown_extensions:
  - toc:
      permalink: false
  - admonition
  - def_list
  - attr_list
  - tables
  - footnotes

extra:
  manifest:
    name: "Trader Manual"
    short_name: "Manual"
    start_url: "/trader-manual/"     # correct for GitHub Pages project sites
    display: "standalone"
    background_color: "#111827"
    theme_color: "#111827"

extra_css:
  - styles/typography.css
  - styles/colors-dark.css
  

extra_javascript:
  - javascripts/open-toc-by-default.js
